title: 郭伦昊的个人主页
email: guolunhao@gmail.com
description: 独行方行羁绊重，挥剑仗得守护心。
baseurl: ''
url: 'https://guolunhao.github.io'
theme: beautiful-jekyll-theme
remote_theme: daattali/beautiful-jekyll
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
